language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run check-coverage
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
